name: LFS Check
author: Mike Lewis (@MPLew-is)
description: Check that all registered binary files use LFS
branding:
  color: gray-dark
  icon: upload-cloud

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        # We don't actually care about LFS file contents, just their integrity.
        lfs: false
    - name: Validate LFS pointers
      run: git lfs fsck --pointers
